[project]
name = "chrome-dino-neat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "neat-python==0.92",
    "numpy>=2.3.2",
    "pygame==2.6.1",
]
